function today() {
  return new Date().toLocaleDateString("en-GB", {
    day: "2-digit", month: "long", year: "numeric",
  });
}

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function generateContract(c, s) {
  const budgetLabels = {
    "under-1k": "Under $1,000", "1k-5k": "$1,000 – $5,000",
    "5k-10k": "$5,000 – $10,000", "10k-25k": "$10,000 – $25,000", "25k-plus": "$25,000+",
  };
  const timelineLabels = {
    "1-2-weeks": "1–2 Weeks", "1-month": "1 Month",
    "2-3-months": "2–3 Months", "3-6-months": "3–6 Months", "6-months-plus": "6+ Months",
  };
  const bizName = s.business_name || "SmartFlow Systems";
  const bizContact = s.your_name ? ` — ${s.your_name}` : "";
  const bizEmail = s.email ? `\n- **Email:** ${s.email}` : "";
  const bizPhone = s.phone ? `\n- **Phone:** ${s.phone}` : "";
  const bizWebsite = s.website ? `\n- **Website:** ${s.website}` : "";

  return `# SERVICE AGREEMENT
## ${bizName} × ${c.company}

**Date:** ${today()}
**Prepared by:** ${bizName}

---

## 1. PARTIES

**Service Provider:**
${bizName}${bizContact}${bizEmail}${bizPhone}${bizWebsite}

**Client:**
- **Name:** ${c.name}
- **Company:** ${c.company}
- **Email:** ${c.email || "—"}
- **Phone:** ${c.phone || "—"}

---

## 2. PROJECT SCOPE

**Project Type:** ${(c.projectType || "").replace(/-/g, " ")}
**Budget Range:** ${budgetLabels[c.budget] || "To be agreed"}
**Estimated Duration:** ${timelineLabels[c.timeline] || "To be agreed"}
**Proposed Start Date:** ${c.startDate || "To be confirmed"}

### Requirements & Objectives

${c.requirements || "To be defined in discovery session."}

---

## 3. DELIVERABLES

- [ ] Detailed project specification document
- [ ] Regular progress updates (cadence to be agreed)
- [ ] Final deliverable(s) as per scope
- [ ] Handover documentation

---

## 4. PAYMENT TERMS

- **Payment schedule:** To be agreed
- **Invoice terms:** 14 days from invoice date
- **Late payment:** 2% per month on overdue amounts

---

## 5. INTELLECTUAL PROPERTY

All work produced under this agreement remains the property of the Client upon receipt of full payment. ${bizName} retains the right to showcase completed work in its portfolio unless otherwise agreed in writing.

---

## 6. CONFIDENTIALITY

Both parties agree to keep all project information, business data, and communications confidential during and after the engagement.

---

## 7. TERMINATION

Either party may terminate this agreement with 14 days written notice. Any work completed prior to termination will be invoiced accordingly.

---

## 8. SIGNATURES

**${bizName}**
Signature: ______________________ Date: ______________

**${c.name} (${c.company})**
Signature: ______________________ Date: ______________

---
*This document was generated by the SFS Business Toolkit on ${today()}.*
`;
}

function generateChecklist(c) {
  return `# Onboarding Checklist — ${c.company}

**Client:** ${c.name} | ${c.company}
**Generated:** ${today()}

---

## Pre-Project

- [ ] Send welcome email to ${c.name}
- [ ] Schedule kick-off call
- [ ] Share this checklist with the team
- [ ] Set up client folder in project management tool
- [ ] Send and collect signed contract
- [ ] Collect initial deposit / confirm payment terms
- [ ] Gather any existing assets (logos, brand guide, copy, etc.)

## Discovery & Planning

- [ ] Conduct kick-off meeting / discovery session
- [ ] Document all client requirements in detail
- [ ] Define project milestones and delivery dates
- [ ] Create and share project timeline
- [ ] Get sign-off on project spec / scope document
- [ ] Set up communication channel (Slack, email thread, etc.)
- [ ] Agree on check-in cadence (weekly, bi-weekly, etc.)

## Project Execution

- [ ] Begin work per agreed timeline
- [ ] Provide first progress update
- [ ] Mid-project review with client
- [ ] Incorporate feedback rounds (agree number upfront)
- [ ] Internal QA / testing before delivery

## Delivery & Handover

- [ ] Deliver final work for client review
- [ ] Address final feedback / revisions
- [ ] Prepare handover documentation
- [ ] Deliver final files / access credentials
- [ ] Confirm client satisfaction
- [ ] Send final invoice

## Post-Project

- [ ] Send thank you / follow-up email
- [ ] Request testimonial / review
- [ ] Add to portfolio (if permission granted)
- [ ] Log project in SFS records
- [ ] Identify upsell / retainer opportunity

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generateClientBrief(c) {
  const budgetLabels = {
    "under-1k": "Under $1,000", "1k-5k": "$1,000 – $5,000",
    "5k-10k": "$5,000 – $10,000", "10k-25k": "$10,000 – $25,000", "25k-plus": "$25,000+",
  };
  return `# Client Brief — ${c.company}

**Date Added:** ${today()}

| Field | Details |
|---|---|
| Client Name | ${c.name} |
| Company | ${c.company} |
| Email | ${c.email || "—"} |
| Phone | ${c.phone || "—"} |
| Project Type | ${(c.projectType || "").replace(/-/g, " ")} |
| Budget | ${budgetLabels[c.budget] || "—"} |
| Start Date | ${c.startDate || "TBC"} |
| Timeline | ${(c.timeline || "").replace(/-/g, " ")} |

## Notes & Requirements

${c.requirements || "No additional notes provided."}

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generateEmailPitch(service, s) {
  const bulletList = service.benefits.map((b) => `- ${b}`).join("\n");
  const senderName = s.your_name || "[Your Name]";
  const senderBusiness = s.business_name || "SmartFlow Systems";
  const senderEmail = s.email || "[Your Email]";
  const senderPhone = s.phone || "[Your Phone]";
  const calendarLink = s.calendar_link || "[Your Calendar Link]";

  return `# Email Pitch — ${service.name}

**Generated:** ${today()}

---

## Subject Line Options

1. Introducing ${service.name} — Built for ${service.audience}
2. Here's how we help ${service.audience} [result]
3. Stop [pain point] — ${service.name} is here

---

## Email Body

**Subject:** Introducing ${service.name}

Hi [First Name],

I wanted to reach out because I think ${service.name} could make a real difference for you.

${service.description}

Here's what you get:

${bulletList}

${service.price ? "**Pricing:** " + service.price : ""}

If this sounds like something you've been looking for, I'd love to chat. ${service.cta}.

Best,
${senderName}
${senderBusiness}
${senderEmail} | ${senderPhone}

---

## Follow-Up Email (send 3–5 days later)

**Subject:** Quick follow-up on ${service.name}

Hi [First Name],

Just circling back on my last message about ${service.name}.

I know your inbox is busy, so I'll keep this short — if ${service.description.toLowerCase()}, we can help.

Would a quick 15-minute call this week work for you?

${calendarLink}

Best,
${senderName}

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generateSocialPosts(service, s) {
  const benefitHighlight = service.benefits[0] || "saving you time and money";
  const bulletList = service.benefits.map((b) => `• ${b}`).join("\n");
  const bizName = s.business_name || "SmartFlow Systems";
  const bizTag = bizName.replace(/\s+/g, "");

  return `# Social Media Posts — ${service.name}

**Generated:** ${today()}

---

## LinkedIn Post

🚀 Introducing ${service.name}

${service.description}

We built this specifically for ${service.audience} — and here's what makes it different:

${bulletList}

${service.price ? service.price + " | " : ""}${service.cta}.

Drop a comment or DM us to learn more. 👇

#${bizTag} #${service.category || "Business"} #${service.audience.split(" ")[0]}Solutions

---

## Twitter / X Post (under 280 chars)

Introducing ${service.name} — built for ${service.audience}.

${benefitHighlight}.

${service.price ? service.price + " | " : ""}${service.cta}. 🚀

---

## Twitter / X Thread

**Tweet 1:**
🧵 We just launched ${service.name}. Here's everything you need to know (thread) 👇

**Tweet 2:**
The problem: ${service.audience} often struggle with [common pain point].

${service.name} was built to fix exactly that.

**Tweet 3:**
Here's what's included:
${service.benefits.map((b, i) => (i + 1) + ". " + b).join("\n")}

**Tweet 4:**
${service.price ? "Pricing: " + service.price : "Interested? Let's talk."}

${service.cta}. Reply or DM us to get started. 🚀

---

## Instagram Caption

✨ ${service.name} is here!

${service.description}

Perfect for ${service.audience} who want to:
${bulletList}

${service.price ? "💰 " + service.price : ""}

👉 ${service.cta} — link in bio!

.
.
.
#${bizTag} #SmallBusiness #BusinessGrowth #${service.category || "Entrepreneur"} #Productivity #BusinessTips

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generateWebsiteSection(service, s) {
  const benefitItems = service.benefits.map((b) => `
      <li class="sfs-benefit-item">
        <span class="sfs-benefit-icon">✓</span>
        <span>${b}</span>
      </li>`).join("");

  const bizName = s.business_name || "SmartFlow Systems";
  const bizWebsite = s.website || "#contact";
  const ctaHref = s.calendar_link || bizWebsite;

  return `<!-- ${service.name} — Website Section -->
<!-- Generated by SFS Business Toolkit on ${today()} -->
<!-- Paste this into your website HTML. Styles are included inline. -->

<section class="sfs-service-section" style="background:#0d1117;color:#e6edf3;padding:80px 20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:760px;margin:0 auto;">
    <div style="text-align:center;margin-bottom:40px;">
      ${s.logo_url ? `<img src="${s.logo_url}" alt="${bizName} logo" style="height:48px;margin-bottom:12px;display:block;margin-left:auto;margin-right:auto;" />` : ""}
      <span style="background:linear-gradient(135deg,#4a9eff,#f0a500);-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-size:13px;font-weight:700;letter-spacing:1px;text-transform:uppercase;">${bizName}</span>
      <h2 style="font-size:36px;font-weight:800;margin:12px 0;line-height:1.2;">${service.name}</h2>
      <p style="font-size:18px;color:#8b949e;line-height:1.6;max-width:560px;margin:0 auto;">${service.description}</p>
    </div>
    <div style="background:#161b22;border:1px solid #30363d;border-radius:16px;padding:32px;margin-bottom:32px;">
      <p style="font-size:13px;font-weight:600;color:#8b949e;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:16px;">Built for ${service.audience}</p>
      <ul style="list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:12px;">${benefitItems}</ul>
    </div>
    <style>
      .sfs-benefit-item { display:flex;align-items:flex-start;gap:12px;font-size:15px;line-height:1.5; }
      .sfs-benefit-icon { width:22px;height:22px;background:rgba(63,185,80,0.15);border:1px solid #3fb950;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;color:#3fb950;flex-shrink:0;margin-top:1px; }
    </style>
    <div style="text-align:center;">
      ${service.price ? '<p style="font-size:15px;color:#8b949e;margin-bottom:16px;">' + service.price + '</p>' : ""}
      <a href="${ctaHref}" style="display:inline-block;background:linear-gradient(135deg,#4a9eff,#2176c7);color:white;font-size:15px;font-weight:700;padding:14px 32px;border-radius:8px;text-decoration:none;">${service.cta}</a>
    </div>
  </div>
</section>
`;
}

function generateOutreachEmail1(p, s) {
  const senderName = s.your_name || "[Your Name]";
  const senderBusiness = s.business_name || "SmartFlow Systems";
  const senderEmail = s.email || "[Your Email]";
  const senderPhone = s.phone || "[Your Phone]";
  const calendarLink = s.calendar_link || "[Your Calendar Link]";

  return `# Email 1 — Introduction
**Prospect:** ${p.name} | ${p.company}
**Service Interest:** ${p.service}
**Generated:** ${today()}

---

## Subject Line Options

1. A quick idea for ${p.company}
2. How we help businesses like ${p.company} with ${p.service}
3. ${senderBusiness} → ${p.company}: worth a conversation?

---

## Email Body

**Subject:** A quick idea for ${p.company}

Hi ${p.name.split(" ")[0]},

I came across ${p.company} and wanted to reach out — I think we could genuinely help you.

At ${senderBusiness}, we specialise in ${p.service} for businesses like yours. We've helped clients save time, reduce friction, and grow their revenue by putting the right systems in place.

${p.notes ? `I noticed that ${p.notes}\n\nThat's exactly the kind of challenge we solve every day.` : `I'd love to learn more about what you're working on and see if there's a fit.`}

Would you be open to a quick 20-minute call this week?

${calendarLink ? `You can grab a time that suits you here: ${calendarLink}` : "Just reply to this email and we'll find a time."}

Best,
${senderName}
${senderBusiness}
${senderEmail}${senderPhone ? " | " + senderPhone : ""}

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generateOutreachEmail2(p, s) {
  const senderName = s.your_name || "[Your Name]";
  const senderBusiness = s.business_name || "SmartFlow Systems";
  const senderEmail = s.email || "[Your Email]";
  const calendarLink = s.calendar_link || "[Your Calendar Link]";

  return `# Email 2 — Follow-Up
**Prospect:** ${p.name} | ${p.company}
**Service Interest:** ${p.service}
**Send:** 4–5 days after Email 1
**Generated:** ${today()}

---

## Subject Line Options

1. Re: A quick idea for ${p.company}
2. Still thinking about ${p.company}...
3. Following up — ${p.service} for ${p.company}

---

## Email Body

**Subject:** Re: A quick idea for ${p.company}

Hi ${p.name.split(" ")[0]},

Just following up on my note from earlier this week — I know inboxes get busy!

I wanted to share one thing: most businesses we work with in ${p.company}'s space tell us their biggest bottleneck before working with us was [common pain point related to ${p.service}]. Sound familiar?

We've put together a short overview of how ${senderBusiness} approaches ${p.service} — happy to walk you through it on a quick call.

No hard sell, just a conversation to see if it makes sense.

${calendarLink ? `Book a slot here: ${calendarLink}` : "Just hit reply and let me know a time that works."}

Best,
${senderName}
${senderBusiness}
${senderEmail}

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generateOutreachEmail3(p, s) {
  const senderName = s.your_name || "[Your Name]";
  const senderBusiness = s.business_name || "SmartFlow Systems";
  const senderEmail = s.email || "[Your Email]";
  const calendarLink = s.calendar_link || "[Your Calendar Link]";

  return `# Email 3 — Final Check-In
**Prospect:** ${p.name} | ${p.company}
**Service Interest:** ${p.service}
**Send:** 7–10 days after Email 2
**Generated:** ${today()}

---

## Subject Line Options

1. Last note from ${senderBusiness}
2. Closing the loop — ${p.company}
3. One last thought for ${p.name.split(" ")[0]}

---

## Email Body

**Subject:** Last note from ${senderBusiness}

Hi ${p.name.split(" ")[0]},

I don't want to overstay my welcome, so this is my last follow-up for now.

If ${p.service} is something ${p.company} is looking to improve in the next few months, I'd love to have a quick chat and show you what's possible.

If the timing isn't right — no problem at all. Feel free to reach out whenever it makes sense.

${calendarLink ? `If you'd like to connect: ${calendarLink}` : "You can reply any time — I'll be here."}

Wishing you and the team at ${p.company} all the best,

${senderName}
${senderBusiness}
${senderEmail}

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

function generatePitchDeckOutline(p, s) {
  const bizName = s.business_name || "SmartFlow Systems";
  const bizWebsite = s.website || "[Your Website]";

  return `# Pitch Deck Outline — ${p.company}
**Prospect:** ${p.name} | ${p.company}
**Service Interest:** ${p.service}
**Prepared by:** ${bizName}
**Date:** ${today()}

---

## Slide 1 — Title Slide

- **Headline:** ${p.service} for ${p.company}
- **Subheadline:** How ${bizName} can help
- **Prepared for:** ${p.name}, ${p.company}
- **Date:** ${today()}

---

## Slide 2 — The Problem

- What challenges does ${p.company} face without the right ${p.service} solution?
- Frame 2–3 specific pain points (e.g. manual processes, lost leads, slow delivery)
- Use a relatable stat or quote if possible
${p.notes ? `\n> Context: ${p.notes}` : ""}

---

## Slide 3 — The Solution

- Introduce ${bizName}'s approach to ${p.service}
- High-level overview of what you do and how it's different
- Focus on outcomes, not features

---

## Slide 4 — How It Works

- Step 1: Discovery & Scope
- Step 2: Build / Implement
- Step 3: Test & Deliver
- Step 4: Ongoing Support (if applicable)

---

## Slide 5 — What's Included

- List the key deliverables relevant to ${p.service}
- Be specific: e.g. "Full build & deployment", "Staff training session", "30-day post-launch support"

---

## Slide 6 — Why ${bizName}

- Key differentiators (speed, quality, communication, track record)
- Brief stats or proof points
- One or two short testimonials or client logos (anonymised if needed)

---

## Slide 7 — Investment

- Pricing tiers or a starting-from price for ${p.service}
- Payment structure (e.g. 50% upfront, 50% on delivery)
- What's NOT included (scope clarity)

---

## Slide 8 — Next Steps

- Step 1: Schedule a discovery call
- Step 2: Receive tailored proposal within 48 hours
- Step 3: Sign off and kick off

**CTA:** ${s.calendar_link || "Book a call at " + bizWebsite}

---

## Slide 9 — Thank You

- ${bizName} contact details
- Website: ${bizWebsite}
- Email: ${s.email || "[Your Email]"}
- Phone: ${s.phone || "[Your Phone]"}

---
*Generated by SFS Business Toolkit on ${today()}.*
`;
}

module.exports = {
  slugify, generateContract, generateChecklist, generateClientBrief,
  generateEmailPitch, generateSocialPosts, generateWebsiteSection,
  generateOutreachEmail1, generateOutreachEmail2, generateOutreachEmail3,
  generatePitchDeckOutline
};
